[[redirects]]
  from = "/openApi/*"
  to = "https://www.kopis.or.kr/openApi/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Host = "munamuna.netlify.app"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
	force = false