[[redirects]]
  from = "/api/*"
  to = "https://www.kopis.or.kr/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
	force = false

[build]
  publish = "build"
  command = "npm run build"
  